allowBuilds:
  "@prisma/client": false
  "@tailwindcss/oxide": true
  "@sentry/cli": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - "@takumi-rs/core-darwin-arm64@1.4.0"
  - "@takumi-rs/core-darwin-x64@1.4.0"
  - "@takumi-rs/core-linux-arm64-gnu@1.4.0"
  - "@takumi-rs/core-linux-arm64-musl@1.4.0"
  - "@takumi-rs/core-linux-x64-gnu@1.4.0"
  - "@takumi-rs/core-linux-x64-musl@1.4.0"
  - "@takumi-rs/core-win32-arm64-msvc@1.4.0"
  - "@takumi-rs/core-win32-x64-msvc@1.4.0"
  - "@takumi-rs/core@1.4.0"
  - "@takumi-rs/helpers@1.4.0"
  - "@takumi-rs/wasm@1.4.0"
  - takumi-js@1.4.0
  - "@sveltejs/kit@2.63.0"
