items=minecraft:skull
nbt.ItemModel=minecraft:pale_oak_button
model=item/hplus_generated
texture=hotf_empty_vertical
nbt.display.Name=regex:(Sweep|Luck of the Forest|Daily Wishes|250 Gifts|Monster Hunter|Tree Whisperer)