items=minecraft:skull
nbt.ItemModel=minecraft:pale_oak_button
model=item/hplus_generated
texture=hotf_empty_horizontal
nbt.display.Name=regex:(Strength Boost|Speed Boost|Deep Waters|Collector|Hunter\'s Luck|Essence Fortune)