items=minecraft:skull
nbt.ItemModel=minecraft:pale_oak_button
model=item/hplus_generated
texture=hotf_empty_cross
nbt.display.Name=regex:(Foraging Fortune|Foraging Madness|Efficient Forager|Early Bird|Forest Strength|Galatea.s Might|Forest Speed)