items=minecraft:planks
model=item/hplus_generated
texture=hotf_cross
nbt.display.Name=regex:(Foraging Fortune|Foraging Madness|Efficient Forager|Early Bird|Forest Strength|Galatea.s Might|Forest Speed)