items=minecraft:skull
nbt.ItemModel=minecraft:stripped_mangrove_log
model=item/hplus_generated
texture=hotf_vertical_disabled
nbt.display.Name=regex:(Sweep|Luck of the Forest|Daily Wishes|250 Gifts|Monster Hunter|Tree Whisperer)
weight=1