type=item
items=minecraft:bow
texture.bow=bingbow
texture.bow_pulling_1=bingbow_pulling_1
texture.bow_pulling_2=bingbow_pulling_2
texture.bow_pulling_0=bingbow_pulling_0
nbt.ExtraAttributes.id=BINGBOW